# TRANSFORMACIÓN DE DATOS

## IMPORTAR PAQUETES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from category_encoders import TargetEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import QuantileTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

#Automcompletar rápido
%config IPCompleter.greedy=True

## IMPORTAR LOS DATOS

1.- Sustituir la ruta del proyecto.

In [2]:
ruta_proyecto = 'C:/Users/eloic/Google Drive/EOI/TFM//01_MANT_PREDICTIVO'

2.- Nombrar los ficheros de datos.

In [3]:
nombre_cat = 'cat_resultado_eda.pickle'
nombre_num = 'num_resultado_eda.pickle'

3.- Cargar los datos.

In [4]:
cat = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_cat)
num = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_num)

4.- Separar la target.

In [5]:
target = cat[['fallo']].copy().reset_index(drop=True)

In [6]:
target['fallo'] = target['fallo'].map( 
                   {'Yes':1 ,'No':0})

In [7]:
target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4919 entries, 0 to 4918
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fallo   4918 non-null   float64
dtypes: float64(1)
memory usage: 38.6 KB

In [8]:
cat.columns

Index(['operador', 'medida_2', 'medida_3', 'fallo', 'mes', 'dia_mes',
       'dia_semana'],
      dtype='object')

## TRANSFORMACIÓN DE CATEGÓRICAS

### One Hot Encoding

#### Variables a aplicar OHE

In [9]:
var_ohe = ['operador', 'medida_2', 'medida_3', 'fallo', 'mes', 'dia_mes','dia_semana']

#### Instanciar

In [10]:
ohe = OneHotEncoder(sparse = False, handle_unknown='ignore')

#### Entrenar y aplicar

In [11]:
cat_ohe = ohe.fit_transform(cat[var_ohe])

#### Guardar como dataframe

In [12]:
cat_ohe = pd.DataFrame(cat_ohe, columns = ohe.get_feature_names_out())

## TRANSFORMACIÓN DE NUMÉRICAS

## UNIFICAR DATASETS TRANSFORMADOS

In [13]:
df = pd.concat([cat_ohe,num.reset_index()],axis = 1).set_index('Date')

In [14]:
df.columns

Index(['operador_Operator1', 'operador_Operator2', 'operador_Operator3',
       'operador_Operator4', 'operador_Operator5', 'operador_Operator6',
       'operador_Operator7', 'operador_Operator8', 'medida_2_0', 'medida_2_1',
       'medida_2_2', 'medida_2_3', 'medida_3_0', 'medida_3_1', 'medida_3_2',
       'fallo_ Yes', 'fallo_No', 'fallo_Yes', 'mes_1', 'mes_2', 'mes_3',
       'mes_4', 'mes_5', 'mes_6', 'mes_7', 'mes_8', 'mes_9', 'mes_10',
       'mes_11', 'mes_12', 'dia_mes_1', 'dia_mes_2', 'dia_mes_3', 'dia_mes_4',
       'dia_mes_5', 'dia_mes_6', 'dia_mes_7', 'dia_mes_8', 'dia_mes_9',
       'dia_mes_10', 'dia_mes_11', 'dia_mes_12', 'dia_mes_13', 'dia_mes_14',
       'dia_mes_15', 'dia_mes_16', 'dia_mes_17', 'dia_mes_18', 'dia_mes_19',
       'dia_mes_20', 'dia_mes_21', 'dia_mes_22', 'dia_mes_23', 'dia_mes_24',
       'dia_mes_25', 'dia_mes_26', 'dia_mes_27', 'dia_mes_28', 'dia_mes_29',
       'dia_mes_30', 'dia_mes_31', 'dia_semana_1', 'dia_semana_2',
       'dia_semana_3', 'dia_semana_4', 'dia_semana_5', 'dia_semana_6',
       'dia_semana_7', 'temperatura', 'humedad', 'medida_1', 'medida_4',
       'medida_5', 'medida_6', 'medida_7', 'medida_8', 'medida_9', 'medida_10',
       'medida_11', 'medida_12', 'medida_13', 'medida_14', 'medida_15',
       'horas_desde_utlimo_fallo', 'hora'],
      dtype='object')

## REESCALAR VARIABLES

### Con Min-Max

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4919 entries, 2016-01-01 02:00:00 to 2016-12-31 23:00:00
Data columns (total 85 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   operador_Operator1        4919 non-null   float64
 1   operador_Operator2        4919 non-null   float64
 2   operador_Operator3        4919 non-null   float64
 3   operador_Operator4        4919 non-null   float64
 4   operador_Operator5        4919 non-null   float64
 5   operador_Operator6        4919 non-null   float64
 6   operador_Operator7        4919 non-null   float64
 7   operador_Operator8        4919 non-null   float64
 8   medida_2_0                4919 non-null   float64
 9   medida_2_1                4919 non-null   float64
 10  medida_2_2                4919 non-null   float64
 11  medida_2_3                4919 non-null   float64
 12  medida_3_0                4919 non-null   float64
 13  medida_3_1                4919 non-null   float64
 14  medida_3_2                4919 non-null   float64
 15  fallo_ Yes                4919 non-null   float64
 16  fallo_No                  4919 non-null   float64
 17  fallo_Yes                 4919 non-null   float64
 18  mes_1                     4919 non-null   float64
 19  mes_2                     4919 non-null   float64
 20  mes_3                     4919 non-null   float64
 21  mes_4                     4919 non-null   float64
 22  mes_5                     4919 non-null   float64
 23  mes_6                     4919 non-null   float64
 24  mes_7                     4919 non-null   float64
 25  mes_8                     4919 non-null   float64
 26  mes_9                     4919 non-null   float64
 27  mes_10                    4919 non-null   float64
 28  mes_11                    4919 non-null   float64
 29  mes_12                    4919 non-null   float64
 30  dia_mes_1                 4919 non-null   float64
 31  dia_mes_2                 4919 non-null   float64
 32  dia_mes_3                 4919 non-null   float64
 33  dia_mes_4                 4919 non-null   float64
 34  dia_mes_5                 4919 non-null   float64
 35  dia_mes_6                 4919 non-null   float64
 36  dia_mes_7                 4919 non-null   float64
 37  dia_mes_8                 4919 non-null   float64
 38  dia_mes_9                 4919 non-null   float64
 39  dia_mes_10                4919 non-null   float64
 40  dia_mes_11                4919 non-null   float64
 41  dia_mes_12                4919 non-null   float64
 42  dia_mes_13                4919 non-null   float64
 43  dia_mes_14                4919 non-null   float64
 44  dia_mes_15                4919 non-null   float64
 45  dia_mes_16                4919 non-null   float64
 46  dia_mes_17                4919 non-null   float64
 47  dia_mes_18                4919 non-null   float64
 48  dia_mes_19                4919 non-null   float64
 49  dia_mes_20                4919 non-null   float64
 50  dia_mes_21                4919 non-null   float64
 51  dia_mes_22                4919 non-null   float64
 52  dia_mes_23                4919 non-null   float64
 53  dia_mes_24                4919 non-null   float64
 54  dia_mes_25                4919 non-null   float64
 55  dia_mes_26                4919 non-null   float64
 56  dia_mes_27                4919 non-null   float64
 57  dia_mes_28                4919 non-null   float64
 58  dia_mes_29                4919 non-null   float64
 59  dia_mes_30                4919 non-null   float64
 60  dia_mes_31                4919 non-null   float64
 61  dia_semana_1              4919 non-null   float64
 62  dia_semana_2              4919 non-null   float64
 63  dia_semana_3              4919 non-null   float64
 64  dia_semana_4              4919 non-null   float64
 65  dia_semana_5              4919 non-null   float64
 66  dia_semana_6              4919 non-null   float64
 67  dia_semana_7              4919 non-null   float64
 68  temperatura               4919 non-null   int64
 69  humedad                   4919 non-null   int64
 70  medida_1                  4919 non-null   int64
 71  medida_4                  4919 non-null   int64
 72  medida_5                  4919 non-null   int64
 73  medida_6                  4919 non-null   int64
 74  medida_7                  4919 non-null   int64
 75  medida_8                  4919 non-null   int64
 76  medida_9                  4919 non-null   int64
 77  medida_10                 4919 non-null   int64
 78  medida_11                 4919 non-null   int64
 79  medida_12                 4919 non-null   int64
 80  medida_13                 4919 non-null   int64
 81  medida_14                 4919 non-null   int64
 82  medida_15                 4919 non-null   int64
 83  horas_desde_utlimo_fallo  4919 non-null   int64
 84  hora                      4919 non-null   int64
dtypes: float64(68), int64(17)
memory usage: 3.2+ MB

Seleccionamos todas variables menos en las que hemos hecho One Hot Encoding.

#### Variables a reescalar con Min-Max

In [16]:
var_mms = df.iloc[:,68:].columns#En este caso desde la 67

In [17]:
var_mms

Index(['temperatura', 'humedad', 'medida_1', 'medida_4', 'medida_5',
       'medida_6', 'medida_7', 'medida_8', 'medida_9', 'medida_10',
       'medida_11', 'medida_12', 'medida_13', 'medida_14', 'medida_15',
       'horas_desde_utlimo_fallo', 'hora'],
      dtype='object')

#### Instanciar

In [18]:
mms = MinMaxScaler()

#### Entrenar y aplicar

In [19]:
df_mms = mms.fit_transform(df[var_mms])

#### Guardar como dataframe

In [20]:
#Añadir sufijos a los nombres
nombres_mms = [variable + '_mms' for variable in var_mms]

#Guardar como dataframe
df_mms = pd.DataFrame(df_mms,columns = nombres_mms)

In [21]:
df_mms

,temperatura_mms,humedad_mms,medida_1_mms,medida_4_mms,medida_5_mms,medida_6_mms,medida_7_mms,medida_8_mms,medida_9_mms,medida_10_mms,medida_11_mms,medida_12_mms,medida_13_mms,medida_14_mms,medida_15_mms,horas_desde_utlimo_fallo_mms,hora_mms
0,0.500000,0.200000,0.674030,0.191810,0.766164,0.520755,0.966056,0.930496,0.617457,0.063578,0.954741,0.521552,0.302802,0.734375,0.826954,0.136842,0.086957
1,0.607143,0.200000,0.466595,0.016164,0.008082,0.429650,0.553879,0.632543,0.146552,0.799030,0.374461,0.120690,0.740302,0.323276,0.371429,0.144361,0.304348
2,0.464286,0.272727,0.140086,0.459591,0.501616,0.864690,0.964978,0.893858,0.861530,0.693427,0.100216,0.507543,0.896552,0.170797,0.181132,0.147368,0.391304
3,0.392857,0.327273,0.199353,0.241379,0.794720,0.854447,0.230603,0.264547,0.088362,0.419181,0.935345,0.655172,0.942349,0.771013,0.510512,0.148872,0.434783
4,0.428571,0.290909,0.842672,0.390625,0.226293,0.844744,0.429418,0.396013,0.276940,0.337823,0.843211,0.261853,0.789332,0.480065,0.864690,0.150376,0.478261
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4914,0.392857,0.309091,0.785560,0.411099,0.837823,0.153639,0.877155,0.213362,0.686961,0.073276,0.345905,0.989224,0.771552,0.965517,0.765499,0.007519,0.782609
4915,0.571429,0.254545,0.421336,0.926724,0.842672,0.034501,0.319504,0.940733,0.357759,0.210668,0.401940,0.731142,0.712284,0.205819,0.137466,0.009023,0.826087
4916,0.357143,0.218182,0.120690,0.355065,0.988685,0.782210,0.641703,0.434806,0.387931,0.491379,0.244073,0.051724,0.711746,0.197737,0.424798,0.010526,0.869565
4917,0.392857,0.218182,0.237069,0.810345,0.527478,0.624798,0.405172,0.519397,0.790948,0.063039,0.535560,0.967672,0.905172,0.753772,0.024259,0.012030,0.913043
4918,0.357143,0.309091,0.131466,0.091056,0.683728,0.352561,0.411638,0.666487,0.175647,0.514009,0.488147,0.815733,0.694504,0.317349,0.750943,0.015038,1.000000

## UNIFICAR DATASETS REESCALADOS

In [22]:
Date = df.index

In [23]:
Date

Index(['2016-01-01 02:00:00', '2016-01-01 07:00:00', '2016-01-01 09:00:00',
       '2016-01-01 10:00:00', '2016-01-01 11:00:00', '2016-01-01 13:00:00',
       '2016-01-01 14:00:00', '2016-01-01 16:00:00', '2016-01-01 17:00:00',
       '2016-01-01 18:00:00',
       ...
       '2016-12-31 07:00:00', '2016-12-31 08:00:00', '2016-12-31 11:00:00',
       '2016-12-31 16:00:00', '2016-12-31 17:00:00', '2016-12-31 18:00:00',
       '2016-12-31 19:00:00', '2016-12-31 20:00:00', '2016-12-31 21:00:00',
       '2016-12-31 23:00:00'],
      dtype='object', name='Date', length=4919)

### Unir todos los dataframes en el tablón analítico

In [24]:
df_tablon = pd.concat([cat_ohe,df_mms,target], axis = 1)

In [25]:
df_tablon.index = Date

In [26]:
df_tablon

,operador_Operator1,operador_Operator2,operador_Operator3,operador_Operator4,operador_Operator5,operador_Operator6,operador_Operator7,operador_Operator8,medida_2_0,medida_2_1,...,medida_9_mms,medida_10_mms,medida_11_mms,medida_12_mms,medida_13_mms,medida_14_mms,medida_15_mms,horas_desde_utlimo_fallo_mms,hora_mms,fallo
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01 02:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.617457,0.063578,0.954741,0.521552,0.302802,0.734375,0.826954,0.136842,0.086957,0.0
2016-01-01 07:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.146552,0.799030,0.374461,0.120690,0.740302,0.323276,0.371429,0.144361,0.304348,1.0
2016-01-01 09:00:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.861530,0.693427,0.100216,0.507543,0.896552,0.170797,0.181132,0.147368,0.391304,0.0
2016-01-01 10:00:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.088362,0.419181,0.935345,0.655172,0.942349,0.771013,0.510512,0.148872,0.434783,0.0
2016-01-01 11:00:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.276940,0.337823,0.843211,0.261853,0.789332,0.480065,0.864690,0.150376,0.478261,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-31 18:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.686961,0.073276,0.345905,0.989224,0.771552,0.965517,0.765499,0.007519,0.782609,0.0
2016-12-31 19:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.357759,0.210668,0.401940,0.731142,0.712284,0.205819,0.137466,0.009023,0.826087,0.0
2016-12-31 20:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.387931,0.491379,0.244073,0.051724,0.711746,0.197737,0.424798,0.010526,0.869565,0.0
2016-12-31 21:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.790948,0.063039,0.535560,0.967672,0.905172,0.753772,0.024259,0.012030,0.913043,0.0
2016-12-31 23:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.175647,0.514009,0.488147,0.815733,0.694504,0.317349,0.750943,0.015038,1.000000,0.0

## GUARDAR DATASET TRAS TRANSFORMACIÓN DE DATOS

En formato pickle para no perder las modificaciones de metadatos.

In [27]:
#Definir los nombres del archivo
ruta_df_tablon = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'df_tablon.pickle'

In [28]:
#Guardar los archivos
df_tablon.to_pickle(ruta_df_tablon)